[package]
name = "hlw-roblox/hlw-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Signal = "sleitnick/signal@2.0.0"
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@1.1.0"
TableUtil = "sleitnick/table-util@1.2.0"
Component = "sleitnick/component@2.4.0"
